{% set version = '1.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mixtools
  version: {{ version|replace("-", "_") }}

source:
  fn: mixtools_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/mixtools_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mixtools/mixtools_{{ version }}.tar.gz
  sha256: 543fd8d8dc8d4b6079ebf491cf97f27d6225e1a6e65d8fd48553ada23ba88d8f

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-mass
    - r-segmented
    - r-survival

  run:
    - r-base
    - r-mass
    - r-segmented
    - r-survival

test:
  commands:
    - $R -e "library('mixtools')"  # [not win]
    - "\"%R%\" -e \"library('mixtools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mixtools
  license: GPL (>= 2)
  summary: Analyzes finite mixture models for various parametric and semiparametric settings.  This
    includes mixtures of parametric distributions (normal, multivariate normal, multinomial,
    gamma), various Reliability Mixture Models (RMMs), mixtures-of-regressions settings
    (linear regression, logistic regression, Poisson regression, linear regression with
    changepoints, predictor-dependent mixing proportions, random effects regressions,
    hierarchical mixtures-of-experts), and tools for selecting the number of components
    (bootstrapping the likelihood ratio test statistic and model selection criteria).  Bayesian
    estimation of mixtures-of-linear-regressions models is available as well as a novel
    data depth method for obtaining credible bands.  This package is based upon work
    supported by the National Science Foundation under Grant No. SES-0518772.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
