# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IdtcJO2ZmokQ9BaCa//9+laTyhj+7pO/ZwiIjpBCgQD6J15P/A2aYsJObD1OgvtyhUx+NgASQmz8wHPMyzlxFUltw1Fr3utgzPKB84aAWSeesSy2RNKR+2gCx4E3lSILOOJx4UtgAAkZ79a4ClSzv8h2vsyCw03y2Z6PQMViZICFS/1g6J7Dca4d/F4n99DiO2c0Oqx7EwMs4UK9DqfVSU39pt8aqsg1ThkuS0gZ+6u/q4dmTuPky2kVBKICxJlFfkVBEVvu0kN38aUZJb5xR0L3rVI9IoPKzqO/yDvn4QXtqSjuavDeXJNLxJbCHsnpMLTFBwZezaZJPX7IafA1pNQN6gvPlx49TsPMm0qdmUCEtmZsUEn+p+I6J9C0wdOuSgNI2u4fik5T4O5sm+eIcWlOmzS7F9JogiHLXfPBOMuCozdNg8bE635qPI9PlpL/pLu2F5+Oxu/wwjMFPPOKcZHkbLCirczeu7l75Nbw1uBXtGjydy5dm0zF/R/PtVkTIFbixbT6yFUMsDCRMGXm4ZP8YR8SkK5PS/qYKtHNocR1Pbw8ePU0HGdwN1zO73jkinNDfMCmWe3ggAYi6p3p7g+OEbSETdjX5oDF2uMebMuJRlL3BAzOEqjgOZyF2p0KHH60sKtZKCqJOLHMlMibzOBliE18PEALu+japzsx/fQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
