appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: IdtcJO2ZmokQ9BaCa//9+laTyhj+7pO/ZwiIjpBCgQD6J15P/A2aYsJObD1OgvtyhUx+NgASQmz8wHPMyzlxFUltw1Fr3utgzPKB84aAWSeesSy2RNKR+2gCx4E3lSILOOJx4UtgAAkZ79a4ClSzv8h2vsyCw03y2Z6PQMViZICFS/1g6J7Dca4d/F4n99DiO2c0Oqx7EwMs4UK9DqfVSU39pt8aqsg1ThkuS0gZ+6u/q4dmTuPky2kVBKICxJlFfkVBEVvu0kN38aUZJb5xR0L3rVI9IoPKzqO/yDvn4QXtqSjuavDeXJNLxJbCHsnpMLTFBwZezaZJPX7IafA1pNQN6gvPlx49TsPMm0qdmUCEtmZsUEn+p+I6J9C0wdOuSgNI2u4fik5T4O5sm+eIcWlOmzS7F9JogiHLXfPBOMuCozdNg8bE635qPI9PlpL/pLu2F5+Oxu/wwjMFPPOKcZHkbLCirczeu7l75Nbw1uBXtGjydy5dm0zF/R/PtVkTIFbixbT6yFUMsDCRMGXm4ZP8YR8SkK5PS/qYKtHNocR1Pbw8ePU0HGdwN1zO73jkinNDfMCmWe3ggAYi6p3p7g+OEbSETdjX5oDF2uMebMuJRlL3BAzOEqjgOZyF2p0KHH60sKtZKCqJOLHMlMibzOBliE18PEALu+japzsx/fQ=}
bot:
  automerge: true
